//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magic8BallServiceClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace= "http://localhost:8733/IMagic8BallService/ObtainAnswerToQuestion")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMagic8BallService")]
    public interface IMagic8BallService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMagic8BallService/GetData", ReplyAction="http://tempuri.org/IMagic8BallService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMagic8BallService/GetData", ReplyAction="http://tempuri.org/IMagic8BallService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMagic8BallService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IMagic8BallService/GetDataUsingDataContractResponse")]
        Magic8BallServiceClient.ServiceReference1.CompositeType GetDataUsingDataContract(Magic8BallServiceClient.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMagic8BallService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IMagic8BallService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Magic8BallServiceClient.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(Magic8BallServiceClient.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMagic8BallService/ObtainAnswerToQuestion", ReplyAction="http://tempuri.org/IMagic8BallService/ObtainAnswerToQuestionResponse")]
        string ObtainAnswerToQuestion(string userQuestion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMagic8BallService/ObtainAnswerToQuestion", ReplyAction="http://tempuri.org/IMagic8BallService/ObtainAnswerToQuestionResponse")]
        System.Threading.Tasks.Task<string> ObtainAnswerToQuestionAsync(string userQuestion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMagic8BallServiceChannel : Magic8BallServiceClient.ServiceReference1.IMagic8BallService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Magic8BallClient : System.ServiceModel.ClientBase<Magic8BallServiceClient.ServiceReference1.IMagic8BallService>, Magic8BallServiceClient.ServiceReference1.IMagic8BallService {
        
        public Magic8BallClient() {
        }
        
        public Magic8BallClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Magic8BallClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Magic8BallClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Magic8BallClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public Magic8BallServiceClient.ServiceReference1.CompositeType GetDataUsingDataContract(Magic8BallServiceClient.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Magic8BallServiceClient.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(Magic8BallServiceClient.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string ObtainAnswerToQuestion(string userQuestion) {
            return base.Channel.ObtainAnswerToQuestion(userQuestion);
        }
        
        public System.Threading.Tasks.Task<string> ObtainAnswerToQuestionAsync(string userQuestion) {
            return base.Channel.ObtainAnswerToQuestionAsync(userQuestion);
        }
    }
}
